### PR TITLE
User can Login

### PR DESCRIPTION
**Pull request by jayjieh**
I have implemented both in angular and spring boot backend the features for the user to be able to login.

### CODE REVIEW

**Comment by GeBeater** [comment]
Unfortunately the application (the frontend) does not start (see compile errors below). That the application starts is one of our minimum requirements. Thus I close the PR without further code comments.

```
barkasse:tiny-task-jayjieh beho$ yarn start
yarn run v1.17.3
$ ng serve
10% building 3/3 modules 0 active｢wds｣: Project is running at http://localhost:4200/webpack-dev-server/
｢wds｣: webpack output is served from /
｢wds｣: 404s will fallback to //index.html

chunk {main} main.js, main.js.map (main) 2.12 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 149 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.15 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 176 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 339 kB [initial] [rendered]
Date: 2020-01-14T17:48:35.793Z - Hash: 20cefcdc2ddcb81197c7 - Time: 4762ms

ERROR in app/app-routing.module.ts:3:29 - error TS2307: Cannot find module 'app/home/home.component'.

3 import {HomeComponent} from "app/home/home.component";
                              ~~~~~~~~~~~~~~~~~~~~~~~~~
app/app-routing.module.ts:5:33 - error TS2307: Cannot find module 'app/register/register.component'.

5 import {RegisterComponent} from "app/register/register.component";
                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
app/app.module.ts:17:29 - error TS2307: Cannot find module './home/home.component'.

17 import {HomeComponent} from './home/home.component';
                               ~~~~~~~~~~~~~~~~~~~~~~~
app/app.module.ts:22:33 - error TS2307: Cannot find module './register/register.component'.

22 import {RegisterComponent} from './register/register.component';
                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
｢wdm｣: Failed to compile.
```

**Comment by jayjieh** [comment]
That's unfortunate, I don't know why its not starting on your end.. Check
the below screenshot.
[image: image.png]

**Comment by GeBeater** [comment]
@jayjieh your post does not contain a screenshot. I assume that you have a different source code on your local machine. The "home" and "register" components imported in app.module.ts and app-routing.module.ts do not exist in your branch.

**Comment by jayjieh** [comment]
Hi Bernd
Apologies, you are right they were missing, I have fixed my commits and
created a new pull request

Regards

**Pull request closed without merging**
